### ISSUE TITLE
Sync for Adobe AEM Webdav

### ISSUE THREAD

**Issue by gregorskii** [millercl/gulp-webdav-sync#11]
Hi there,

I am getting back around to using this plugin and I have more information on the issues I am seeing uploading files.

I think I made a Issue a while back about this, but I can't seem to find it.

I am have ignored the unlink events in `gulp-watch` and it works now. But this plugin could be updated to support the responses from AEM. What do you think would be needed if I were to make a PR?

Thanks

---

Config:

```
const baseOptions = {
    clean: false,
    hostname: config.aem.defaultUrl,
    port: config.aem.defaultPort,
    protocol: 'http:',
    log: process.env.DEBUG === 'true' ? 'log' : 'error'
  };

  const reload = () => {
    plugins.browserSync.reload();
  };

  gulp.task('aem:sync:webdav:clientlibs', () => {
    const base = `${config.paths.aemRoot}/etc/clientlibs`;
    const options = Object.assign({}, baseOptions, {
      base,
      auth: `${config.aem.username}:${config.aem.password}`,
      pathname: '/etc/clientlibs/'
    });

    return plugins.watch(
      `${base}/**`,
      { readDelay: 250 }
    )
      .pipe(plugins.webdavSync(options))
      .pipe(plugins.fn(reload))
    ;
  });
```

This is the debug stream:

```
[gulp-webdav-sync] [log] $dest_propfind
[gulp-webdav-sync] [log]  .getcontentlength 33310
[gulp-webdav-sync] [log]  .getlastmodified 2017-04-11T23:07:27.000Z
[gulp-webdav-sync] [log]  .stat 200
[gulp-webdav-sync] [log]  .resourcetype undefined
[gulp-webdav-sync] 204 project/icons/favicon.ico
[gulp-webdav-sync] [log] $vinyl.event unlink
[gulp-webdav-sync] [log] $vinyl_path /src/main/content/jcr_root/etc/clientlibs/project/scripts/client.js
[gulp-webdav-sync] [log] $base_dir /src/main/content/jcr_root/etc/clientlibs
[gulp-webdav-sync] [log] $dest_url http://localhost:4502/etc/clientlibs/project/scripts/client.js
<?xml version="1.0" encoding="UTF-8" standalone="no"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>http://localhost:4502/etc/clientlibs/project/scripts/client.js</D:href><D:propstat><D:prop><D:creationdate>2017-04-11T23:07:27Z</D:creationdate><D:getetag>"2624324-1491952047911"</D:getetag><jcr:lastModifiedBy xmlns:jcr="http://www.jcp.org/jcr/1.0">admin</jcr:lastModifiedBy><D:lockdiscovery/><D:displayname>client.js</D:displayname><D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock><D:getlastmodified>Tue, 11 Apr 2017 23:07:27 GMT</D:getlastmodified><D:iscollection>0</D:iscollection><D:getcontenttype>application/javascript</D:getcontenttype><D:getcontentlength>2624324</D:getcontentlength><D:resourcetype/></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response></D:multistatus>
[gulp-webdav-sync] [log] $dest_propfind
[gulp-webdav-sync] [log]  .getcontentlength 2624324
[gulp-webdav-sync] [log]  .getlastmodified 2017-04-11T23:07:27.000Z
[gulp-webdav-sync] [log]  .stat 200
[gulp-webdav-sync] [log]  .resourcetype undefined
[gulp-webdav-sync] 204 project/scripts/client.js
```

Whats happening is on request to AEM's Webdav port: http://localhost:4502/webdav I am getting a response back from AEM that the item is not found, but the response is HTML:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
    <head><title>404 Not Found</title></head>
    <body>
        <h1>Not Found</h1>
        <p>Cannot serve request to /scripts/client.js in org.apache.sling.jcr.webdav.impl.servlets.SimpleWebDavServlet</p>

        <h3>Request Progress:</h3>
<pre>
      0 TIMER_START{Request Processing}
      0 COMMENT timer_end format is {&lt;elapsed msec&gt;,&lt;timer name&gt;} &lt;optional message&gt;
      0 LOG Method=PROPFIND, PathInfo=/scripts/client.js
      0 TIMER_START{ResourceResolution}
      0 TIMER_END{0,ResourceResolution} URI=/scripts/client.js resolves to Resource=NonExistingResource, path=/scripts/client.js
      0 LOG Resource Path Info: SlingRequestPathInfo: path=&apos;/scripts/client.js&apos;, selectorString=&apos;null&apos;, extension=&apos;js&apos;, suffix=&apos;null&apos;
      0 TIMER_START{ServletResolution}
      0 TIMER_START{resolveServlet(/scripts/client.js)}
      0 TIMER_END{0,resolveServlet(/scripts/client.js)} Using servlet org.apache.sling.jcr.webdav.impl.servlets.SimpleWebDavServlet
      0 TIMER_END{0,ServletResolution} URI=/scripts/client.js handled by Servlet=org.apache.sling.jcr.webdav.impl.servlets.SimpleWebDavServlet
      0 LOG Applying Requestfilters
      0 LOG Calling filter: com.adobe.granite.resourceresolverhelper.impl.ResourceResolverHelperImpl
      0 LOG Calling filter: org.apache.sling.bgservlets.impl.BackgroundServletStarterFilter
      0 LOG Calling filter: com.adobe.granite.rest.impl.servlet.ApiResourceFilter
      0 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
      0 LOG Calling filter: com.adobe.granite.httpcache.impl.InnerCacheFilter
      0 LOG Calling filter: org.apache.sling.rewriter.impl.RewriterFilter
      0 LOG Calling filter: com.adobe.cq.mcm.campaign.servlets.CampaignCopyTracker
      0 LOG Calling filter: com.day.cq.wcm.core.impl.WCMRequestFilter
      0 LOG Calling filter: com.adobe.cq.history.impl.HistoryRequestFilter
      1 LOG Calling filter: com.adobe.granite.optout.impl.OptOutFilter
      1 LOG Calling filter: com.day.cq.wcm.foundation.forms.impl.FormsHandlingServlet
      1 LOG Calling filter: com.adobe.cq.social.commons.cors.CORSAuthenticationFilter
      1 LOG Calling filter: com.day.cq.analytics.provisioning.impl.UserAuthenticationRequestFilter
      1 LOG Calling filter: org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter
      1 LOG Calling filter: com.day.cq.wcm.mobile.core.impl.redirect.RedirectFilter
      1 LOG RedirectFilter did not redirect (not redirecting in author mode)
      1 LOG Calling filter: com.day.cq.wcm.core.impl.warp.TimeWarpFilter
      1 LOG Calling filter: com.day.cq.wcm.core.impl.AuthoringUIModeServiceImpl
      1 LOG Calling filter: org.apache.sling.security.impl.ContentDispositionFilter
      1 LOG Calling filter: com.adobe.granite.csrf.impl.CSRFFilter
      1 LOG Calling filter: com.adobe.granite.requests.logging.impl.RequestLoggerImpl
      1 LOG Calling filter: com.day.cq.dam.core.impl.servlet.ActivityRecordHandler
      1 LOG Calling filter: com.day.cq.dam.core.impl.assetlinkshare.AdhocAssetShareAuthHandler
      1 LOG Calling filter: com.adobe.cq.social.ugcbase.security.impl.SaferSlingPostServlet
      1 LOG Applying Componentfilters
      1 LOG Calling filter: com.day.cq.wcm.core.impl.WCMComponentFilter
      1 LOG Calling filter: com.day.cq.wcm.core.impl.WCMDebugFilter
      1 LOG Calling filter: com.day.cq.personalization.impl.TargetComponentFilter
      1 TIMER_START{org.apache.sling.jcr.webdav.impl.servlets.SimpleWebDavServlet#0}
      1 LOG Applying Error filters
      1 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
      1 LOG Calling filter: org.apache.sling.rewriter.impl.RewriterFilter
      1 TIMER_START{handleError:status=404}
      1 TIMER_END{0,handleError:status=404} Using handler /libs/sling/servlet/errorhandler/404.jsp
      3 LOG Found processor for post processing ProcessorConfiguration: {contentTypes=[text/html], order=-1, active=true, valid=true, processErrorResponse=true, pipeline=(generator=Config(type=htmlparser, config={}), transformers=(Config(type=linkchecker, config={}), Config(type=mobile, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-mobile: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), Config(type=mobiledebug, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-mobiledebug: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), Config(type=contentsync, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-contentsync: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), serializer=Config(type=htmlwriter, config={}))}
      3 TIMER_END{3,Request Processing} Dumping SlingRequestProgressTracker Entries
</pre>


        <hr>
        <address>Apache Sling</address>
    </body>
</html>
```

This trips up this line:

https://github.com/millercl/gulp-webdav-sync/blob/master/index.js#L606

And throws this error:

```
Error: Unexpected close tag
Line: 61
Column: 11
Char: >
    at error (/projects/Pulls/gulp-webdav-sync/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/projects/Pulls/gulp-webdav-sync/node_modules/sax/lib/sax.js:693:7)
    at closeTag (/projects/Pulls/gulp-webdav-sync/node_modules/sax/lib/sax.js:887:9)
    at SAXParser.write (/projects/Pulls/gulp-webdav-sync/node_modules/sax/lib/sax.js:1452:13)
    at Parser.exports.Parser.Parser.parseString (/projects/Pulls/gulp-webdav-sync/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/projects/Pulls/gulp-webdav-sync/node_modules/xml2js/lib/xml2js.js:7:59)
    at Object.exports.parseString (/projects/Pulls/gulp-webdav-sync/node_modules/xml2js/lib/xml2js.js:540:19)
    at IncomingMessage.<anonymous> (/projects/Pulls/gulp-webdav-sync/index.js:608:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
```

And then crashes the gulp process.

The order of operations that is happening:

1) I build the `client.js` code using webpack
2) I bundle up the `client.js` code and send it to AEM using MVN
3) I modify the source files that create `client.js`
4) Webpack triggers a rebuild of the assets, and also deletes the files from the folder webdav sync is watching
5) Presumably `gulp-watch` detects the unlink event on the file, and the add link at ~ the same time
6) `gulp-watch` emits the vinyl event to this plugin
7) this plugin seems to try to delete the asset on the remote server
8) the unlink works on the remote server, but it expects that the asset is on the remote server to add it back?

I have checked out this repo and linked it as the default for any other project under node 7.7.2.

**Comment by millercl** [comment]
Thanks for the HTML paste.

Does webpack update the files by deleting and then recreating them? Perhaps an option to suppress unlink/delete, either an instance boolean or a file glob, would facilitate a work-around.

PROPFIND is being called before DELETE (e9efe23cfc264d433be03d234c65993378300a70); this may not be necessary. A new condition in [_propfind](https://github.com/millercl/gulp-webdav-sync/blob/d2a0aff62ff6952e369cffdaf6412103aab43dac/index.js#L601-L616) to compare the DOCTYPE before attempting XML parsing might prevent this error. [404 is apparently a valid response](https://stackoverflow.com/questions/1683912/correct-response-for-propfind-on-a-resource-that-does-not-exist), [but there is no condition for it](https://github.com/millercl/gulp-webdav-sync/blob/d2a0aff62ff6952e369cffdaf6412103aab43dac/index.js#L183).

**Comment by gregorskii** [comment]
Yes in this case I am using clean-webpack-plugin to ensure the aem clientlibs are wiped.

Suppressing the unlink events gets it working, I guess the main action item here is to handle the 404. 

I can oook into that, what would be your suggestion, test for it and ignore it? Or emit an error, but let the library continue?

**Comment by millercl** [comment]
9fb6d179070efe180292632b2659c40ee97a334f on [branch '#11'](https://github.com/millercl/gulp-webdav-sync/tree/%2311) might work for you

**Comment by millercl** [comment]
"Error: Unexpected close tag" appears to be caused by xml2js parsing an unexpected document structure. [v2.0.2](https://github.com/millercl/gulp-webdav-sync/releases/tag/v2.0.2) on [npm](https://www.npmjs.com/package/gulp-webdav-sync) calls back a `null` parse result, instead of calling `xml2js.parseString` on the content, if the HTTP header `content-type` is not XML. The expectation is that AEM's 404 page would have a different content-type, such as `text/html`.
