### ISSUE TITLE
Self signed certificate.

### ISSUE THREAD

**Issue by MobiusHorizons** [millercl/gulp-webdav-sync#5]
Sites which use self signed certificates have no way of disabling the node error 'Hostname/IP doesn't match certificate's altnames'.

**Comment by dimanech** [comment]
Have the same problem. How can I disable certificate check?

**Comment by MobiusHorizons** [comment]
In your gulp file:

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

**Comment by dimanech** [comment]
Thanks for reply! But this cause another error:
[01:41:24] Error: Unexpected close tag
Line: 10
Column: 7
Char: >
at error (/path/node_modules/gulp-webdav-sync/node_modules/xml2js/node_modules/sax/lib/sax.js:666:10)
at strictFail (/path//node_modules/gulp-webdav-sync/node_modules/xml2js/node_modules/sax/lib/sax.js:692:7)
at closeTag (/path/node_modules/gulp-webdav-sync/node_modules/xml2js/node_modules/sax/lib/sax.js:885:9)
at Object.write (/path/node_modules/gulp-webdav-sync/node_modules/xml2js/node_modules/sax/lib/sax.js:1444:13)
at Parser.exports.Parser.Parser.parseString (/path/node_modules/gulp-webdav-sync/node_modules/xml2js/lib/xml2js.js:503:31)
at Parser.parseString (/path/node_modules/gulp-webdav-sync/node_modules/xml2js/lib/xml2js.js:7:59)
at Object.exports.parseString (/path/node_modules/gulp-webdav-sync/node_modules/xml2js/lib/xml2js.js:535:19)
at IncomingMessage.<anonymous> (/path/node_modules/gulp-webdav-sync/index.js:517:14)
	at IncomingMessage.emit (events.js:117:20)
	at _stream_readable.js:944:16
	
	events.js:72
	throw er; // Unhandled 'error' event
	^
	Error: Protocol:https: not supported.
	at Object.exports.request (http.js:1845:11)
	at _mkcol (/path/node_modules/gulp-webdav-sync/index.js:488:16)
	at init (/path/node_modules/gulp-webdav-sync/index.js:212:11)
	at /path/node_modules/gulp-webdav-sync/index.js:156:9
	at /path/node_modules/gulp-webdav-sync/index.js:521:9
	at Parser.<anonymous> (/path/node_modules/gulp-webdav-sync/node_modules/xml2js/lib/xml2js.js:488:18)
		at Parser.emit (events.js:95:17)
		at Object.onerror (/path/node_modules/gulp-webdav-sync/node_modules/xml2js/lib/xml2js.js:309:26)
		at emit (/path/node_modules/gulp-webdav-sync/node_modules/xml2js/node_modules/sax/lib/sax.js:639:35)
		at error (/path/node_modules/gulp-webdav-sync/node_modules/xml2js/node_modules/sax/lib/sax.js:668:5)

**Comment by MobiusHorizons** [comment]
Not sure what is going on there, it worked for me, but I'm not a developer on this project.

Best of luck.

**Comment by millercl** [comment]
Is this error emitted as an event?

**Comment by dimanech** [comment]
This is error on start

**Comment by dimanech** [comment]
@MobiusHorizons Thank you for you help! Really appreciate this

**Comment by millercl** [comment]
What if 'rejectUnauthorized' is used in the options parameter?

var options = {
  // etc.
  , rejectUnauthorized: false
}

https://nodejs.org/api/https.html#https_https_request_options_callback

**Comment by dimanech** [comment]
This works well! Thank you for support!

**Comment by millercl** [comment]
please justify the certificate's invalidity. you may post the x509 and
hostname if you'd like.

e.g.
openssl x509 -in localhost.pem -text
cat /etc/hosts

**Comment by MobiusHorizons** [comment]
@millercl, The use case in question here, is uploading files to a development server. It is relatively common to use self-signed certificates for development servers, for cost reasons. This is especially true when using corporate frameworks where the server cannot be run locally. 

In such circumstances, it would be helpful to have an option that would allow insecure certificates instead of pasting the code in the gulpfile. 

This is akin to curl's `--insecure` flag.

**Comment by millercl** [comment]
@MobiusHorizons thanks

Self-signed certificated can still be authenticated using optional configuration.

1) Use a Common Name (CN) subject in the certificate that matches your server's hostname.
```shell
hostname # with shell
nslookup <IP> # remote
```

2) If not using DNS, add the certificate's CN to your client's operating system host resolution table.
```shell
echo <IP> <CN> >> /etc/hosts
```

For 1 and 2, passing (a copy of) the same certificate as the certificate authority (CA) will authenticate.
```js
var options = {
  , ca: fs.readFileSync( 'cert.pem' )
}
```

3) Disable connection authentication. _Insecure_
```js
var options = {
  , rejectUnauthorized: false
}
```
This permits any authentication error, not just `[Hostname/IP doesn't match certificate's altnames]`. However, it is per connection agent, so less permissive than
```js
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0
```

**Comment by MobiusHorizons** [comment]
@millercl  thanks, I think these options provide what i need.
