### ISSUE TITLE
Error:  Non-whitespace before first tag

### ISSUE THREAD

**Issue by moonweazel** [millercl/gulp-webdav-sync#7]
Hello.

I am using gulp webdav sync and I am getting the following: 

>Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: 4
    at error (D:\louRepo\FabricUI\FabricUI\node_modules\gulp-webdav-sync\node_modules\xml2js\node_modules\sax\lib\sax.js:666:10)
    at strictFail (D:\louRepo\FabricUI\FabricUI\node_modules\gulp-webdav-sync\node_modules\xml2js\node_modules\sax\lib\sax.js:692:7)
    at beginWhiteSpace (D:\louRepo\FabricUI\FabricUI\node_modules\gulp-webdav-sync\node_modules\xml2js\node_modules\sax\lib\sax.js:965:7)
    at Object.write (D:\louRepo\FabricUI\FabricUI\node_modules\gulp-webdav-sync\node_modules\xml2js\node_modules\sax\lib\sax.js:1017:11)
    at Parser.exports.Parser.Parser.parseString (D:\louRepo\FabricUI\FabricUI\node_modules\gulp-webdav-sync\node_modules\xml2js\lib\xml2js.js:503:31)
    at Parser.parseString (D:\louRepo\FabricUI\FabricUI\node_modules\gulp-webdav-sync\node_modules\xml2js\lib\xml2js.js:7:59)
    at Object.exports.parseString (D:\louRepo\FabricUI\FabricUI\node_modules\gulp-webdav-sync\node_modules\xml2js\lib\xml2js.js:535:19)
    at IncomingMessage.<anonymous> (D:\louRepo\FabricUI\FabricUI\node_modules\gulp-webdav-sync\index.js:533:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16

Please let me know if there is anything else you need from me.

**Comment by millercl** [comment]
Sorry, this error is originating from a dependency, [xml2js](
https://github.com/Leonidas-from-XIV/node-xml2js). To reproduce this
behavior, it would help to know what WebDAV implementation is being used,
or to have a trace of the HTTP session from packet capture utility like
[Wireshark](https://www.wireshark.org/).
